export const AI_ASSISTANT_ACTIONS = {
  GENERAL_HELP: 'GENERAL_HELP',

  GET_APPOINTMENTS:
    'GET_APPOINTMENTS',

  CHECK_APPOINTMENT_AVAILABILITY:
    'CHECK_APPOINTMENT_AVAILABILITY',

  CREATE_APPOINTMENT:
    'CREATE_APPOINTMENT',

  CANCEL_APPOINTMENT:
    'CANCEL_APPOINTMENT',

  GET_INVOICES:
    'GET_INVOICES',

  GET_TREATMENTS:
    'GET_TREATMENTS',

  GET_MESSAGE_CONTACTS:
    'GET_MESSAGE_CONTACTS',

  SEND_MESSAGE:
    'SEND_MESSAGE',
}

export const AI_ASSISTANT_ACTION_VALUES =
  Object.values(
    AI_ASSISTANT_ACTIONS,
  )

export const AI_CONFIRMATION_ACTIONS = [
  AI_ASSISTANT_ACTIONS.CREATE_APPOINTMENT,
  AI_ASSISTANT_ACTIONS.CANCEL_APPOINTMENT,
  AI_ASSISTANT_ACTIONS.SEND_MESSAGE,
]