export const APPOINTMENT_STATUSES = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW',
}

export const APPOINTMENT_STATUS_VALUES = Object.values(
  APPOINTMENT_STATUSES,
)